resources:
  - name: c3isetup
    type: GitRepo
    configuration:
      gitProvider: maheshg_github
      path: conan-io/c3i-setup

pipelines:
  - name: TestBash
    configuration:
      environmentVariables:
        readOnly:
          pipe: yes
        check: 'true'
    steps:
      - name: run1
        type: Bash
        configuration:
          environmentVariables:
            foo: bar
            fizz: bin
          inputResources:
            - name: c3isetup
        execution:
          # onStart: do
          onExecute:
            - echo res_path is $res_c3isetup_resourcePath
            - cd $res_c3isetup_resourcePath
            - ls
            - pwd
            - gcloud version
            - gcloud config set project cpe-c3i-dev
            - gcloud auth activate-service-account --key-file=int_c3i_dev_kube_json_key
            - gcloud container clusters get-credentials conan-dev --zone us-west1-a --project cpe-c3i-dev
            - kubectl version
            - kubectl get pods -n conan
            - echo foo is $foo and fizz is $fizz
            - echo pipe is $pipe
            - echo check is $check
            - add_run_variables firststg=1,2
      - name: firststg1
        type: Bash
        configuration:
          environmentVariables:
            check: 'true'
          inputSteps:
            - name: run1
        execution:
          onExecute:
            - echo first stage $firststg
            - if [[ ! "$firststg" =~ "1" ]]; then echo need to skip; exit; fi
            - echo pipe is $pipe
            - echo check is $check
      - name: firststg2
        type: Bash
        configuration:
          inputSteps:
            - name: run1
        execution:
          onExecute:
            - if [[ ! "$firststg" =~ "2" ]]; then echo need to skip; exit; fi
            - echo pipe is $pipe
      - name: firststg3
        type: Bash
        configuration:
          inputSteps:
            - name: run1
        execution:
          onExecute:
            - if [[ ! "$firststg" =~ "3" ]]; then echo need to skip; exit; fi
            - echo pipe is $pipe
