pipelines:
  - name: TestBash
    configuration:
      environmentVariables:
        readOnly:
          pipe: yes
        check: 'true'
    steps:
      - name: run1
        type: Bash
        configuration:
          environmentVariables:
            foo: bar
            fizz: bin
        execution:
          # onStart: do
          onExecute:
            - printenv
            - echo foo is $foo and fizz is $fizz
            - echo pipe is $pipe
            - echo check is $check
      - name: firststg1
        type: Bash
        configuration:
          environmentVariables:
            check: 'true'
          inputSteps:
            - name: run1
        execution:
          # onStart: do
          onExecute:
            - echo pipe is $pipe
            - echo check is $check
      - name: firststg2
        type: Bash
        configuration:
          inputSteps:
            - name: run1
        execution:
          # onStart: do
          onExecute:
            - echo pipe is $pipe
      - name: firststg3
        type: Bash
        configuration:
          inputSteps:
            - name: run1
        execution:
          # onStart: do
          onExecute:
            - echo pipe is $pipe
