pipelines:
  - name: TestBash
    configuration:
      environmentVariables:
        readOnly:
          pipe: yes
    steps:
      - name: run
        type: Bash
        configuration:
          affinityGroup: 123
          foo: bar
          timeoutSeconds: abc
          chronological: maybe
          environmentVariables:
            foo: bar
            fizz: bin
        execution:
          onExecute:
            - echo foo is $foo and fizz is $fizz
