pipelines:
  - name: TestBash
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            normal:
              - foo: bar
              - fizz: bin
        execution:
          onExecute:
            - echo foo is $foo and fizz is $fizz
