pipelines:
  - name: TestBash
    configuration:
      environmentVariables:
        readOnly:
          pipe: yes
    steps:
      - name: run1
        type: Bash
        configuration:
          environmentVariables:
            foo: bar
            fizz: bin
        execution:
          # onStart: do
          onExecute:
            - printenv
            - echo foo is $foo and fizz is $fizz
            - echo pipe is $pipe
            - export pipe=no
            - echo pipe is $pipe
      - name: run2
        type: Bash
        configuration:
          environmentVariables:
            foo: bar
            fizz: bin
        execution:
          # onStart: do
          onExecute:
            - printenv
            - echo foo is $foo and fizz is $fizz
            - echo pipe is $pipe
