resources:
  - name: dockerImage
    type: Image
    configuration:
      registry: art_docker
      imageName: mill.jfrog.info:12052/docker/busybox
      imageTag: latest
  - name: dockerbuild_repo
    type: GitRepo
    configuration:
      path: skylark05/dockerbuild
      gitProvider: github
  - name: docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: docker_example
      buildNumber: 1
      
pipelines:
  - name: docker_example
    steps:
      - name: build_docker
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: mill.jfrog.info:12052/docker/ragesh
          dockerImageTag: $pipeline_name.$run_number
          inputResources:
            - name: dockerbuild_repo
          #integrations:
          #  - name: art
      #- name: push_docker_image
      #  type: PushArtifactoryPackage
      #  configuration:
      #    targetRepo: docker
      #    integrations:
      #      - name: art
      #    inputSteps:
      #      - name: build_docker
      #- name: publish_docker_build
      #  type: PublishBuildInfo
      #  configuration:
      #    integrations:
      #      - name: art
      #   inputSteps:
      #      - name: push_docker_image
      #    outputResources:
      #      - name: docker_build_info


