pipelines:
  - name: pipeline_win_teset
    steps:
      - name: power_build
        type: PowerShell
        execution:
          onStart:
            - echo "Testing"
          onExecute:
            - echo "msbuild"
            - vssetup
